version: '3'
services:
  app:
    container_name: hypebold_api
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
    env_file: 
      - .env
  mongo:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

volumes:
  data:
