FROM node:20-alpine

ARG HYPEBOLD_MONGO
ARG HYPEBOLD_JWT_SECRET
ARG HYPEBOLD_ADMIN_SECRET

ENV NODE_ENV development
ENV HYPEBOLD_MONGO=${HYPEBOLD_MONGO}
ENV HYPEBOLD_JWT_SECRET=${HYPEBOLD_JWT_SECRET}
ENV HYPEBOLD_ADMIN_SECRET=${HYPEBOLD_ADMIN_SECRET}

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install @nestjs/cli -g
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "run", "start:dev"]
