name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.13.2
      uses: actions/setup-node@v1
      with:
        node-version: '16.13.2'
    - run: npm install
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        hypebold_secret_key: ${{ secrets.HYPEBOLD_SECRET_KEY }}
        hypebold_mongo_uri: ${{ secrets.HYPEBOLD_MONGO_URI }}
        hypebold_admin_key: ${{ secrets.HYPEBOLD_ADMIN_KEY }}
      with:
        name: kokaipatrik/hypebold-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./DockerfileProd
        tags: latest
        buildargs: hypebold_secret_key, hypebold_mongo_uri, hypebold_admin_key
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: GITHUB_USERNAME, GITHUB_TOKEN
        script: |
          docker rm $(docker stop $(docker ps -a -q --filter ancestor=kokaipatrik/hypebold-api --format="{{.ID}}"))
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker pull kokaipatrik/hypebold-api:latest
          docker network create --driver bridge hypebold || true
          docker run --name hypebold_api -p 3000:3000 --network hypebold --restart always kokaipatrik/hypebold-api:latest
          echo 'Deployment was successful to DigitalOcean.'