name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        HYPEBOLD_MONGO: ${{ secrets.HYPEBOLD_MONGO }}
        HYPEBOLD_JWT_SECRET: ${{ secrets.HYPEBOLD_JWT_SECRET }}
        HYPEBOLD_ADMIN_SECRET: ${{ secrets.HYPEBOLD_ADMIN_SECRET }}
      with:
        name: kokaipatrik/hypebold-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./DockerfileProd
        tags: latest
        buildargs: HYPEBOLD_MONGO, HYPEBOLD_JWT_SECRET, HYPEBOLD_ADMIN_SECRET
    - name: Deploy package to DigitalOcean
      uses: appleboy/ssh-action@master
      env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: GITHUB_USERNAME, GITHUB_TOKEN
        script: |
          docker stop $(docker ps -q --filter ancestor=kokaipatrik/hypebold-api)
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker pull kokaipatrik/hypebold-api:latest
          docker run -dit -p 3000:3000 --restart always kokaipatrik/hypebold-api:latest
          docker system prune -a -f
